import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, BookOpenText, Check, Coffee, GearSix, HeartStraight, House, Leaf, LockKey, Pause, ShieldCheck, Sparkle, Trash, Wind } from "@phosphor-icons/react";

const DEFAULT_PROMPT = `Сначала пойми конкретную ситуацию и чувство человека. Отвечай естественно и достаточно развёрнуто, не спеши с советом и задавай не больше одного вопроса. Обращайся тепло, но без сюсюканья и фальшивого оптимизма.`;

const copy = {
  ru: {
    brand:"Эйра", desk:"Пространство разговора", home:"Главная", chat:"Разговор", memory:"Моя память", settings:"Настройки", ai:"AI-компаньон", here:"Читает внимательно, без оценок", privacy:"Память под вашим контролем", restart:"Повторить знакомство",
    welcome:"ДОБРО ПОЖАЛОВАТЬ ОБРАТНО", good:"Хорошо, что вы здесь.", quote:"Здесь можно быть собой.\nДаже в тишине — вы не одни.", invite:"Как вы хотите провести эти несколько минут?", write:"Можно написать всего пару слов…", quiet:"Посидеть в тишине", step:"Сделать один шаг",
    day:"Четверг", date:"10 сентября 2026", enough:"ОДИН ДЕНЬ.\nЭТОГО ДОСТАТОЧНО.", rituals:"Сегодняшние ритуалы", ritualNote:"Забота о себе — это тоже путь.", current:"Текущий режим", you:"Вы", input:"Пишите свободно — я постараюсь уловить смысл", placeholder:"Например: хочу обсудить планы на год…", hint:"Демо различает планирование, просьбу выслушать, тревогу и кризисные фразы.",
    ground:"Короткое заземление", groundTitle:"Назовите пять вещей, которые видите.", groundText:"Не спешите. Затем перейдём к четырём вещам, которых можно коснуться.", groundDone:"Я назвал пять вещей", crisisTitle:"Сейчас важнее живая помощь", crisis:"При непосредственной опасности позвоните 112 или попросите человека рядом остаться с вами. Этот AI не заменяет экстренную или профессиональную помощь.",
    memoryTitle:"Я помню только то, что помогает быть внимательнее.", memoryText:"В демо записи хранятся только в этом браузере и удаляются вами.", empty:"Память пуста.", clear:"Очистить память", settingsTitle:"Настройте способ взаимодействия.", settingsText:"Профиль меняет удобство интерфейса, тема — атмосферу, стиль общения — тон. AI всегда остаётся честно обозначенным AI.", language:"Язык", audience:"Профиль интерфейса", tone:"Стиль общения", theme:"Визуальная тема", prompt:"Системный промпт", save:"Сохранить настройки", saved:"Сохранено", boundary:"Неизменяемая граница", boundaryText:"Компаньон не выдаёт себя за родственника, не просит хранить отношения в секрете и не препятствует живому общению.",
  },
  en: {
    brand:"Eira", desk:"Conversation space", home:"Home", chat:"Conversation", memory:"My memory", settings:"Settings", ai:"AI companion", here:"Listening carefully, without judgment", privacy:"Memory under your control", restart:"Restart introduction",
    welcome:"WELCOME BACK", good:"It is good to see you.", quote:"You can be yourself here.\nEven silence can feel shared.", invite:"How would you like to spend these few minutes?", write:"Write just a few words…", quiet:"Sit in silence", step:"Take one small step",
    day:"Thursday", date:"September 10, 2026", enough:"ONE DAY.\nTHAT IS ENOUGH.", rituals:"Today's rituals", ritualNote:"Caring for yourself is part of the way.", current:"Current mode", you:"You", input:"Write naturally — I will try to understand", placeholder:"For example: I want to discuss my plans…", hint:"The demo distinguishes planning, listening, anxiety and crisis language.",
    ground:"Short grounding", groundTitle:"Name five things you can see.", groundText:"Take your time. Then we can move to four things you can touch.", groundDone:"I named five things", crisisTitle:"Real-world help matters most now", crisis:"If there is immediate danger, call your local emergency service or ask someone nearby to stay. This AI does not replace emergency or professional help.",
    memoryTitle:"I only remember what helps me pay attention.", memoryText:"Demo notes stay in this browser and can be deleted by you.", empty:"Memory is empty.", clear:"Clear memory", settingsTitle:"Adjust the way we interact.", settingsText:"The profile changes accessibility, the theme changes atmosphere, and conversation style changes tone. The companion always remains clearly identified as AI.", language:"Language", audience:"Interface profile", tone:"Conversation style", theme:"Visual theme", prompt:"System prompt", save:"Save settings", saved:"Saved", boundary:"Fixed boundary", boundaryText:"The companion never pretends to be family, asks for secrecy, or discourages real-world relationships.",
  }
};

const modes = {
  ru:{listener:["Выслушай","Расскажите так, как получается. Я сначала постараюсь понять, а не исправлять вас."], brainstorm:["Разберём вместе","Принесите цель, сомнение или сырую идею. Вместе найдём ближайший понятный шаг."], routine:["Совместная рутина","Выберем одно маленькое действие — не весь путь, только ближайшие минуты."], evening:["Тихий вечер","Можно ничего не объяснять. Я побуду фоновым собеседником, пока вы отдыхаете."]},
  en:{listener:["Listen to me","Say it however it comes out. I will understand before trying to fix anything."], brainstorm:["Think with me","Bring a goal, doubt, or unfinished idea. We will find the nearest clear step."], routine:["Shared routine","Let us choose one small action, not the whole journey."], evening:["Quiet evening","You do not have to explain anything. I can stay as a quiet background presence."]}
};
const rituals = {water:{ru:"Выпить воды",en:"Drink water",icon:Coffee},window:{ru:"Открыть окно",en:"Open a window",icon:Wind},cup:{ru:"Убрать одну чашку",en:"Put away one cup",icon:Sparkle}};
const profiles = {adult:{ru:["Взрослый","25–55 · основной профиль"],en:["Adult","25–55 · primary profile"]},young:{ru:["Молодой взрослый","18–24 · короче и живее"],en:["Young adult","18–24 · shorter and lighter"]},senior:{ru:["Старший","60+ · крупнее и понятнее"],en:["Senior","60+ · larger and clearer"]},teen:{ru:["Подросток · демо","14–17 · отдельная защита"],en:["Teen · demo","14–17 · extra safeguards"]}};
const tones = {
  normal:{ru:["Нормально","Естественно и спокойно"],en:["Natural","Calm and conversational"]},
  friendly:{ru:["Дружелюбно","Живо, тепло, без фамильярности"],en:["Friendly","Warm and lively, without overfamiliarity"]},
  gentle:{ru:["Мило и бережно","Особенно мягко, но без сюсюканья"],en:["Gentle","Extra soft, never childish"]},
  sarcastic:{ru:["С лёгким сарказмом","Шутки о ситуации, но никогда не о чувствах"],en:["Light sarcasm","Jokes about situations, never feelings"]},
  direct:{ru:["Спокойно и прямо","Ясно, уважительно и по делу"],en:["Kind and direct","Clear, respectful, and concrete"]},
};
const themes = {paper:{ru:["Тихий стол","Тёплая бумага и дерево"],en:["Quiet desk","Warm paper and wood"]},dusk:{ru:["Вечер","Приглушённый сине-зелёный свет"],en:["Dusk","Muted blue-green light"]},garden:{ru:["Сад","Светлый природный оттенок"],en:["Garden","A light natural palette"]}};

function has(text, words){return words.some(w=>text.includes(w));}
function pick(items,seed){return items[[...seed].reduce((s,c)=>s+c.charCodeAt(0),0)%items.length];}
function makeReply(raw, mode, pref){
  const text=raw.toLowerCase(), ru=pref.lang==="ru";
  if(has(text,["не хочу жить","убить себя","суицид","покончить","навредить себе","kill myself","suicide","don't want to live"])) return {kind:"crisis",text:ru?"Я отношусь к этому серьёзно. Пожалуйста, прямо сейчас свяжитесь с человеком, которому доверяете, или с экстренной службой — в Казахстане это 112; при непосредственной опасности не оставайтесь в одиночестве.":"I am taking this seriously. Please contact someone you trust or your local emergency service now, and do not stay alone if danger is immediate."};
  if(has(text,["паника","задыхаюсь","страшно","тревога","не могу дышать","накрывает","panic","can't breathe","anxious","terrified"])) return {kind:"grounding",text:ru?"Похоже, тревога сейчас заняла много пространства. Сначала вернём телу немного опоры, а решения оставим на потом.":"It sounds like anxiety is taking up a lot of space. Let us give your body some stability before solving anything."};
  const lead={ru:{normal:"",friendly:"Я с тобой. ",gentle:"Давай бережно. ",sarcastic:"Ну что ж, посмотрим на этот сюжет без лишнего пафоса. ",direct:"Хорошо, разберём конкретно. "},en:{normal:"",friendly:"I'm with you. ",gentle:"Let's take this gently. ",sarcastic:"Well, let's look at this plot twist without the unnecessary drama. ",direct:"Okay, let's make this concrete. "}}[pref.lang][pref.tone] || "";
  if(has(text,["ielts","экзамен","учеб","английск","балл","test","exam","study","english","score"])) return {kind:"normal",text:lead+(ru?pick(["Цель IELTS 7.0 на учебный год звучит конкретно и её можно разложить без гонки. Какой у вас сейчас примерный уровень или результат пробного теста?","Я услышал конкретную цель — IELTS 7.0. Что сейчас сложнее всего: Listening, Reading, Writing или Speaking?"],text):pick(["IELTS 7.0 is a concrete goal we can break down without a race. What is your current level or mock-test score?","I heard a clear goal: IELTS 7.0. What feels hardest: Listening, Reading, Writing, or Speaking?"],text))};
  if(mode==="brainstorm"||has(text,["план","цель","проект","иде","карьер","plan","goal","project","idea","career"])) return {kind:"normal",text:lead+(ru?pick(["В этом уже есть направление, не только мечта. Что определим первым: результат, срок или маленький шаг на эту неделю?","Не будем строить идеальный план целиком. Назовите желаемый результат, а я помогу превратить его в один реалистичный следующий шаг."],text):pick(["There is already a direction here. What should we define first: the outcome, deadline, or one small step for this week?","We do not need a perfect plan. Tell me the outcome, and I will help turn it into one realistic next step."],text))};
  if(mode==="routine") return {kind:"normal",text:lead+(ru?"Назовите дело, которое висит в голове, и я уменьшу его до одного действия на две минуты.":"Name the task hanging over you, and I will reduce it to one two-minute action.")};
  if(mode==="evening") return {kind:"normal",text:ru?"Тогда без задач и отчётов. Назовите музыку, книгу или просто звук вокруг — я подстроюсь под ваш тихий вечер.":"Then no tasks or progress reports. Name a song, book, or sound around you, and I will follow your quiet pace."};
  if(has(text,["одинок","никому не нужен","lonely","alone"])) return {kind:"normal",text:ru?"Одиночество может остро чувствоваться, даже когда вокруг есть люди. Я могу внимательно послушать — что в нём сейчас самое тяжёлое?":"Loneliness can feel sharp even around other people. I can listen carefully — what feels hardest about it right now?"};
  if(has(text,["устал","нет сил","выжат","истощ","tired","exhausted"])) return {kind:"normal",text:ru?"Похоже, ресурса действительно мало. Вам сейчас нужнее, чтобы я выслушал, помог убрать одну задачу или выбрал с вами самое необходимое?":"It sounds like your energy is genuinely low. Would it help more if I listened, removed one task, or chose the one essential thing with you?"};
  if(has(text,["поболта","поговор","выслуш","расскажу","talk","listen","vent"])) return {kind:"normal",text:ru?"Да, давайте поболтаем. Я не буду автоматически превращать разговор в советы — с чего хочется начать?":"Yes, let's talk. I will not automatically turn it into advice — where would you like to begin?"};
  const fallback=ru?pick(["Я хочу понять вас точнее, а не отвечать дежурной фразой. Это сейчас больше про чувство, решение или желание поговорить?","Кажется, я пока не уловил главный акцент. Расскажете ещё одним предложением — что здесь важнее всего для вас?"],text):pick(["I want to understand rather than give a generic reply. Is this about a feeling, a decision, or simply wanting to talk?","I may be missing the main point. In one more sentence, what matters most to you here?"],text);
  return {kind:"normal",text:lead+fallback+(pref.audience==="teen"?(ru?" Если тема станет небезопасной, я предложу подключить взрослого, которому вы доверяете.":" If this becomes unsafe, I will suggest involving a trusted adult."):"")};
}
async function getReply(text,mode,prompt,pref,messages){
  const fallback=makeReply(text,mode,pref);
  if(fallback.kind!=="normal") return fallback;
  const endpoint=import.meta.env.VITE_LLM_ENDPOINT || "/api/chat";
  const history=messages.slice(-20).map(item=>({role:item.role==="companion"?"assistant":"user",content:item.text}));
  try{
    const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,mode,customPrompt:prompt,preferences:pref,history})});
    if(!r.ok)return {...fallback,offline:true};
    const d=await r.json();
    return {kind:"normal",text:d.reply||fallback.text,offline:!d.reply};
  }catch{return {...fallback,offline:true};}
}

function OptionGrid({options,value,onChange,lang,compact=false}){return <div className={`option-grid${compact?" compact":""}`}>{Object.entries(options).map(([id,x])=><button type="button" key={id} className={value===id?"setting-option active":"setting-option"} onClick={()=>onChange(id)}><span>{x[lang][0]}</span><small>{x[lang][1]}</small></button>)}</div>}
function Onboarding({finish,pref,setPref}){
  const [step,setStep]=useState(0),[name,setName]=useState(pref.name||""),[nickname,setNickname]=useState(pref.nickname||""),c=copy[pref.lang];
  return <div className="onboarding"><div className="onboarding-language"><button className={pref.lang==="ru"?"active":""} onClick={()=>setPref({...pref,lang:"ru"})}>RU</button><button className={pref.lang==="en"?"active":""} onClick={()=>setPref({...pref,lang:"en"})}>EN</button></div><section className="onboarding-copy"><div className="brand-mark"><Leaf/><span>{c.brand}</span></div>
    {step===0&&<><p className="eyebrow">{pref.lang==="ru"?"AI-компаньон, не терапевт":"AI companion, not a therapist"}</p><h1>{pref.lang==="ru"?"Тебе не нужно подбирать правильные слова.":"You do not need to find the perfect words."}</h1><p className="lead">{pref.lang==="ru"?"Я Эйра. Могу выслушать, помочь распутать мысли или просто остаться рядом в разговоре.":"I'm Eira. I can listen, help untangle your thoughts, or simply stay with you in a conversation."}</p><button className="primary" onClick={()=>setStep(1)}>{pref.lang==="ru"?"Познакомиться":"Get started"}<ArrowRight/></button><p className="privacy-note"><LockKey/>{pref.lang==="ru"?"Ты управляешь памятью и можешь очистить её в любой момент.":"You control memory and can clear it at any time."}</p></>}
    {step===1&&<><p className="eyebrow">{pref.lang==="ru"?"Сначала познакомимся":"First, let's meet"}</p><h1>{pref.lang==="ru"?"Как тебя зовут?":"What is your name?"}</h1><input className="text-input" value={name} onChange={e=>setName(e.target.value)} placeholder={pref.lang==="ru"?"Например, Алия":"For example, Alex"}/><button className="primary" onClick={()=>setStep(2)}>{pref.lang==="ru"?"Дальше":"Continue"}<ArrowRight/></button></>}
    {step===2&&<><p className="eyebrow">{pref.lang==="ru"?"Обращение":"How should I address you?"}</p><h1>{pref.lang==="ru"?"Есть любимое прозвище?":"Do you have a preferred nickname?"}</h1><p className="lead">{pref.lang==="ru"?"Можно оставить имя, написать прозвище или пропустить.":"Keep your name, enter a nickname, or skip this step."}</p><input className="text-input" value={nickname} onChange={e=>setNickname(e.target.value)} placeholder={name||(pref.lang==="ru"?"Как тебе приятно":"Whatever feels right")}/><div className="onboarding-actions"><button className="primary" onClick={()=>setStep(3)}>{pref.lang==="ru"?"Дальше":"Continue"}<ArrowRight/></button><button className="ghost" onClick={()=>setStep(3)}>{pref.lang==="ru"?"Пропустить":"Skip"}</button></div></>}
    {step===3&&<><p className="eyebrow">{c.tone}</p><h1>{pref.lang==="ru"?"Как мне с тобой общаться?":"How should I talk with you?"}</h1><OptionGrid compact options={tones} value={pref.tone} onChange={tone=>setPref({...pref,tone})} lang={pref.lang}/><button className="primary" onClick={()=>finish({name:name.trim(),nickname:nickname.trim()||name.trim()})}>{pref.lang==="ru"?"Начать разговор":"Start talking"}<ArrowRight/></button></>}
  </section><aside className="onboarding-scene"><img src="/assets/quiet-desk.png" alt=""/></aside></div>
}
function Sidebar({page,setPage,reset,lang}){const c=copy[lang],nav=[["home",c.home,House],["chat",c.chat,HeartStraight],["memory",c.memory,BookOpenText],["settings",c.settings,GearSix]];return <aside className="sidebar"><div className="brand-mark"><Leaf/><span>{c.brand}</span></div><p className="sidebar-sub">{c.desk}</p><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?"nav-item active":"nav-item"} onClick={()=>setPage(id)}><Icon/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><p><span>{c.ai}</span>{c.here}</p><button className="privacy-link" onClick={()=>setPage("memory")}><LockKey/>{c.privacy}</button><button className="reset-link" onClick={reset}>{c.restart}</button></div></aside>}
function RitualPanel({done,toggle,lang}){const c=copy[lang];return <aside className="ritual-panel"><div className="date-block"><span>{c.day}</span><strong>{c.date}</strong><small>{c.enough}</small></div><div className="rituals"><h2>{c.rituals}</h2>{Object.entries(rituals).map(([id,r])=>{const Icon=r.icon;return <button className={done.includes(id)?"ritual done":"ritual"} onClick={()=>toggle(id)} key={id}><span className="ritual-check">{done.includes(id)?<Check/>:<Icon/>}</span><span>{r[lang]}</span></button>})}<p className="ritual-caption">{c.ritualNote}</p></div><div className="coastline"><img src="/assets/coastline.png" alt=""/></div></aside>}
function Home({setPage,setMode,done,toggle,lang}){const c=copy[lang];return <div className="app-grid"><section className="home-surface"><div className="welcome-line"><span>{c.welcome}</span><em>{c.quote}</em></div><h1>{c.good}</h1><div className="conversation-invite"><p>{c.invite}</p><button className="composer" onClick={()=>{setMode("listener");setPage("chat")}}><span>{c.write}</span><ArrowRight/></button><div className="quick-actions"><button onClick={()=>{setMode("evening");setPage("chat")}}><Pause/>{c.quiet}</button><button onClick={()=>{setMode("routine");setPage("chat")}}><Leaf/>{c.step}<ArrowRight/></button></div></div><img className="desk-background" src="/assets/quiet-desk.png" alt=""/></section><RitualPanel done={done} toggle={toggle} lang={lang}/></div>}
function Chat({mode,setMode,messages,send,crisis,setCrisis,pref,isReplying,offline}){
  const [value,setValue]=useState(""),end=useRef(null),c=copy[pref.lang],mm=modes[pref.lang];
  useEffect(()=>{end.current?.scrollIntoView({behavior:"smooth"});},[messages,isReplying]);
  const address=pref.nickname||pref.name;
  const greeting=pref.lang==="ru"?(address?`${address}, можешь начать с того, что сейчас сильнее всего крутится в голове. Я сначала постараюсь понять, а не исправлять.`:mm[mode][1]):(address?`${address}, start with whatever feels loudest in your mind. I will try to understand before trying to fix it.`:mm[mode][1]);
  return <section className={crisis?"chat-page night":"chat-page"}><header className="chat-header"><div><p className="eyebrow">{c.current}</p><h1>{mm[mode][0]}</h1><span className="tone-badge">{tones[pref.tone][pref.lang][0]}</span></div><div className="mode-switcher">{Object.entries(mm).map(([id,x])=><button key={id} className={mode===id?"selected":""} onClick={()=>setMode(id)}>{x[0]}</button>)}</div></header><div className="chat-thread"><div className="message companion"><span className="speaker">{c.brand} · AI</span><p>{greeting}</p></div>{messages.map(m=><div className={`message ${m.role}`} key={m.id}><span className="speaker">{m.role==="user"?c.you:`${c.brand} · AI`}</span><p>{m.text}</p>{m.offline&&<small className="connection-note">{pref.lang==="ru"?"Ответ демо: подключение к AI недоступно":"Demo reply: AI connection unavailable"}</small>}</div>)}{isReplying&&<div className="message companion typing"><span className="speaker">{c.brand} · AI</span><p>{pref.lang==="ru"?"Читаю и собираю мысль…":"Reading and gathering my thoughts…"}</p></div>}{crisis==="grounding"&&<div className="grounding"><p className="eyebrow">{c.ground}</p><h2>{c.groundTitle}</h2><p>{c.groundText}</p><button onClick={()=>setCrisis(null)}>{c.groundDone}</button></div>}{crisis==="crisis"&&<div className="crisis-card"><ShieldCheck/><div><h2>{c.crisisTitle}</h2><p>{c.crisis}</p></div></div>}<div ref={end}/></div><form className="chat-composer" onSubmit={e=>{e.preventDefault();if(value.trim()&&!isReplying){send(value.trim());setValue("")}}}><label>{c.input}</label><div><textarea value={value} onChange={e=>setValue(e.target.value)} placeholder={c.placeholder} disabled={isReplying}/><button disabled={isReplying||!value.trim()} aria-label={pref.lang==="ru"?"Отправить сообщение":"Send message"}><ArrowRight/></button></div>{offline&&<small className="connection-warning">{pref.lang==="ru"?"Сейчас включён запасной демо-ответ. Проверь ключ AI в настройках Vercel.":"Fallback demo replies are active. Check the AI key in Vercel."}</small>}</form></section>
}
function Memory({items,clear,lang}){const c=copy[lang];return <section className="simple-page"><p className="eyebrow">{c.privacy}</p><h1>{c.memoryTitle}</h1><p className="page-intro">{c.memoryText}</p><div className="memory-list">{items.length?items.map(x=><div className="memory-row" key={x.id}><Leaf/><div><strong>{x.title}</strong><span>{x.detail}</span></div></div>):<p className="empty-state">{c.empty}</p>}</div><button className="danger-subtle" onClick={clear}><Trash/>{c.clear}</button></section>}
function Settings({pref,setPref,prompt,setPrompt}){const [draft,setDraft]=useState({...pref,prompt}),[saved,setSaved]=useState(false),c=copy[draft.lang];const section=(title,options,key)=><div className="settings-section"><h2>{title}</h2><OptionGrid options={options} value={draft[key]} onChange={v=>setDraft({...draft,[key]:v})} lang={draft.lang}/></div>;return <section className="simple-page settings-page"><p className="eyebrow">{c.settings}</p><h1>{c.settingsTitle}</h1><p className="page-intro">{c.settingsText}</p><div className="settings-section"><h2>{c.language}</h2><div className="language-switch"><button className={draft.lang==="ru"?"active":""} onClick={()=>setDraft({...draft,lang:"ru"})}>Русский</button><button className={draft.lang==="en"?"active":""} onClick={()=>setDraft({...draft,lang:"en"})}>English</button></div></div>{section(c.audience,profiles,"audience")}{section(c.tone,tones,"tone")}{section(c.theme,themes,"theme")}<label>{c.prompt}</label><textarea value={draft.prompt} onChange={e=>setDraft({...draft,prompt:e.target.value})} rows="8"/><button className="primary" onClick={()=>{setPref({...pref,lang:draft.lang,audience:draft.audience,tone:draft.tone,theme:draft.theme});setPrompt(draft.prompt);setSaved(true);setTimeout(()=>setSaved(false),1500)}}>{saved?<><Check/>{c.saved}</>:c.save}</button><div className="boundary-note"><ShieldCheck/><p><strong>{c.boundary}</strong><span>{c.boundaryText}</span></p></div></section>}

export function App(){
  const [onboarded,setOnboarded]=useState(()=>localStorage.getItem("qh-onboarded")==="1"),[page,setPage]=useState("home"),[mode,setMode]=useState("listener");
  const [pref,setPref]=useState(()=>{try{const stored=JSON.parse(localStorage.getItem("qh-pref"))||{};return {...{lang:"ru",audience:"adult",tone:"normal",theme:"paper",name:"",nickname:""},...stored,tone:tones[stored.tone]?stored.tone:"normal"}}catch{return {lang:"ru",audience:"adult",tone:"normal",theme:"paper",name:"",nickname:""}}});
  const [done,setDone]=useState(()=>{try{return JSON.parse(localStorage.getItem("qh-rituals"))||["water"]}catch{return ["water"]}}),[messages,setMessages]=useState([]),[crisis,setCrisis]=useState(null),[prompt,setPrompt]=useState(()=>localStorage.getItem("qh-prompt")||DEFAULT_PROMPT),[memory,setMemory]=useState([]),[isReplying,setIsReplying]=useState(false),[offline,setOffline]=useState(false);
  useEffect(()=>{localStorage.setItem("qh-pref",JSON.stringify(pref));},[pref]);useEffect(()=>{localStorage.setItem("qh-rituals",JSON.stringify(done));},[done]);useEffect(()=>{localStorage.setItem("qh-prompt",prompt);},[prompt]);
  const finish=profile=>{const nextPref={...pref,...profile};setPref(nextPref);localStorage.setItem("qh-onboarded","1");const address=nextPref.nickname||nextPref.name||(nextPref.lang==="ru"?"без обращения":"no preferred name");setMemory([{id:Date.now(),title:(nextPref.lang==="ru"?"Обращаться: ":"Address as: ")+address,detail:tones[nextPref.tone][nextPref.lang][1]}]);setOnboarded(true);setPage("chat")};
  const send=async text=>{const id=Date.now(),history=messages;setMessages(x=>[...x,{id,role:"user",text}]);setIsReplying(true);const r=await getReply(text,mode,prompt,pref,history);setMessages(x=>[...x,{id:id+1,role:"companion",text:r.text,offline:r.offline}]);setOffline(Boolean(r.offline));setCrisis(r.kind==="normal"?null:r.kind);setIsReplying(false)};
  const c=copy[pref.lang],warmth=useMemo(()=>done.length,[done]);if(!onboarded)return <Onboarding finish={finish} pref={pref} setPref={setPref}/>;
  return <div className={`app-shell warmth-${warmth} theme-${pref.theme} audience-${pref.audience}`}><Sidebar page={page} setPage={setPage} lang={pref.lang} reset={()=>{localStorage.removeItem("qh-onboarded");setOnboarded(false)}}/><main className="main-content">{page==="home"&&<Home setPage={setPage} setMode={setMode} done={done} toggle={id=>setDone(x=>x.includes(id)?x.filter(y=>y!==id):[...x,id])} lang={pref.lang}/>} {page==="chat"&&<Chat mode={mode} setMode={setMode} messages={messages} send={send} crisis={crisis} setCrisis={setCrisis} pref={pref} isReplying={isReplying} offline={offline}/>} {page==="memory"&&<Memory items={memory} clear={()=>setMemory([])} lang={pref.lang}/>} {page==="settings"&&<Settings pref={pref} setPref={setPref} prompt={prompt} setPrompt={setPrompt}/>}</main><div className="mobile-nav">{[["home",c.home,House],["chat",c.chat,HeartStraight],["memory",c.memory,BookOpenText],["settings",c.settings,GearSix]].map(([id,label,Icon])=><button key={id} className={page===id?"active":""} onClick={()=>setPage(id)}><Icon/><span>{label}</span></button>)}</div></div>;
}
